import { describe, expect, it } from "vitest";

import plugin from "../src/plugin";

describe("plugin export", () => {
    it("exposes rules and configs", () => {
        expect(plugin.rules).toBeDefined();
        expect(plugin.configs).toBeDefined();
        expect(plugin.rules["class-match-filename"]).toBeDefined();
        expect(plugin.rules["consistent-source-extension"]).toBeDefined();
        expect(plugin.rules["consistent-symbol-description"]).toBeDefined();
        expect(plugin.rules["disallow-import"]).toBeDefined();
        expect(plugin.rules["max-identifier-blocks"]).toBeDefined();
        expect(plugin.rules["no-assign-mutated-array"]).toBeDefined();
        expect(plugin.rules["no-at-sign-import"]).toBeDefined();
        expect(plugin.rules["no-at-sign-internal-import"]).toBeDefined();
        expect(plugin.rules["no-chain-coalescence-mixture"]).toBeDefined();
        expect(plugin.rules["no-commented-out-code"]).toBeDefined();
        expect(plugin.rules["no-const-enum"]).toBeDefined();
        expect(plugin.rules["no-deprecated"]).toBeDefined();
        expect(plugin.rules["no-enum"]).toBeDefined();
        expect(plugin.rules["no-foreach"]).toBeDefined();
        expect(plugin.rules["no-implicit-any-catch"]).toBeDefined();
        expect(plugin.rules["no-index-import"]).toBeDefined();
        expect(plugin.rules["no-internal-modules"]).toBeDefined();
        expect(plugin.rules["no-internal"]).toBeDefined();
        expect(plugin.rules["no-language-mixing"]).toBeDefined();
        expect(plugin.rules["no-misused-generics"]).toBeDefined();
        expect(plugin.rules["no-negated-conditions"]).toBeDefined();
        expect(plugin.rules["no-nodejs-modules"]).toBeDefined();
        expect(plugin.rules["no-param-reassign"]).toBeDefined();
        expect(plugin.rules["no-restricted-syntax"]).toBeDefined();
        expect(plugin.rules["no-relative-parent-import"]).toBeDefined();
        expect(plugin.rules["no-self-import"]).toBeDefined();
        expect(plugin.rules["no-shadow"]).toBeDefined();
        expect(plugin.rules["no-sibling-import"]).toBeDefined();
        expect(plugin.rules["no-t"]).toBeDefined();
        expect(plugin.rules["no-unnecessary-template-literal"]).toBeDefined();
        expect(plugin.rules["no-expression-empty-lines"]).toBeDefined();
        expect(plugin.rules["only-export-name"]).toBeDefined();
        expect(plugin.rules["no-underscore-export"]).toBeDefined();
        expect(plugin.rules["no-unnecessary-as-const"]).toBeDefined();
        expect(plugin.rules["no-unnecessary-break"]).toBeDefined();
        expect(plugin.rules["no-unnecessary-initialization"]).toBeDefined();
        expect(plugin.rules["prefer-arrow-function-property"]).toBeDefined();
        expect(plugin.rules["prefer-const-require"]).toBeDefined();
        expect(plugin.rules["prefer-interface"]).toBeDefined();
        expect(plugin.rules["prefer-less-than"]).toBeDefined();
        expect(plugin.rules["prefer-only-export"]).toBeDefined();
        expect(plugin.rules["require-jsdoc"]).toBeDefined();
        expect(plugin.rules["require-syntax"]).toBeDefined();
        expect(plugin.rules["restrict-identifier-characters"]).toBeDefined();
        expect(plugin.rules["sort-call-signature"]).toBeDefined();
        expect(plugin.rules["sort-construct-signature"]).toBeDefined();
        expect(plugin.rules["switch-case-spacing"]).toBeDefined();
        expect(plugin.rules["throw-error"]).toBeDefined();
        expect(plugin.rules["typescript/array-callback-return-type"]).toBeDefined();
        expect(plugin.rules["typescript/class-methods-use-this"]).toBeDefined();
        expect(plugin.rules["typescript/consistent-array-type-name"]).toBeDefined();
        expect(
            plugin.rules["typescript/define-function-in-one-statement"]
        ).toBeDefined();
        expect(plugin.rules["typescript/exhaustive-switch"]).toBeDefined();
        expect(plugin.rules["typescript/no-boolean-literal-type"]).toBeDefined();
        expect(plugin.rules["typescript/no-complex-declarator-type"]).toBeDefined();
        expect(plugin.rules["typescript/no-complex-return-type"]).toBeDefined();
        expect(plugin.rules["typescript/no-empty-interfaces"]).toBeDefined();
        expect(plugin.rules["typescript/no-inferrable-types"]).toBeDefined();
        expect(plugin.rules["typescript/no-multi-type-tuples"]).toBeDefined();
        expect(plugin.rules["typescript/no-never"]).toBeDefined();
        expect(plugin.rules["typescript/no-unsafe-object-assign"]).toBeDefined();
        expect(plugin.rules["typescript/prefer-array-type-alias"]).toBeDefined();
        expect(plugin.rules["typescript/prefer-class-method"]).toBeDefined();
        expect(plugin.rules["typescript/prefer-readonly-array"]).toBeDefined();
        expect(plugin.rules["typescript/prefer-readonly-map"]).toBeDefined();
        expect(plugin.rules["typescript/prefer-readonly-property"]).toBeDefined();
        expect(plugin.rules["typescript/prefer-readonly-set"]).toBeDefined();
        expect(plugin.rules["typescript/require-prop-type-annotation"]).toBeDefined();
        expect(plugin.rules["typescript/require-this-void"]).toBeDefined();
        expect(plugin.rules["underscore-internal"]).toBeDefined();
        expect(
            plugin.configs.recommended.rules["etc-misc/no-assign-mutated-array"]
        ).toBe("error");
        expect(
            plugin.configs.recommended.rules["etc-misc/no-deprecated"]
        ).toBe("warn");
        expect(
            plugin.configs.recommended.rules["etc-misc/no-implicit-any-catch"]
        ).toBe("error");
        expect(plugin.configs.recommended.rules["etc-misc/no-internal"]).toBe(
            "error"
        );
        expect(plugin.configs.recommended.rules["etc-misc/no-t"]).toBe(
            "error"
        );
    });
});
