/**
 * @packageDocumentation
 * Sidebar structure for the primary documentation section under `docs/`.
 */
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/** Main sidebar configuration for the default docs plugin instance. */
const sidebars: SidebarsConfig = {
    docs: [
        {
            className: "sb-doc-intro",
            id: "intro",
            label: "🏁 Intro",
            type: "doc",
        },
        {
            className: "sb-doc-getting-started",
            id: "getting-started",
            label: "🚀 Getting Started",
            type: "doc",
        },
        {
            className: "sb-cat-guides",
            collapsed: false,
            customProps: {
                badge: "playbooks",
            },
            type: "category",
            label: "🧭 Guides",
            link: {
                description:
                    "Practical playbooks for migration, documentation hygiene, and content planning.",
                title: "Guides",
                type: "generated-index",
            },
            items: [
                {
                    dirName: "guides",
                    type: "autogenerated",
                },
            ],
        },
        {
            className: "sb-cat-architecture",
            collapsed: true,
            customProps: {
                badge: "adr",
            },
            type: "category",
            label: "🏗️ Architecture",
            link: {
                description:
                    "Architecture Decision Records (ADRs) that explain key documentation and plugin design choices.",
                title: "Architecture Decisions",
                type: "generated-index",
            },
            items: [
                {
                    dirName: "architecture/adr",
                    type: "autogenerated",
                },
            ],
        },
        {
            className: "sb-cat-developer",
            collapsed: true,
            customProps: {
                badge: "api",
            },
            type: "category",
            label: "🛠 Dev",
            link: {
                type: "doc",
                id: "developer/api/index",
            },
            items: [
                {
                    className: "sb-doc-releasing",
                    id: "releasing",
                    label: "🚢 Releasing",
                    type: "doc",
                },
                {
                    className: "sb-doc-api-overview",
                    id: "developer/api/index",
                    label: "📘 API Overview",
                    type: "doc",
                },
                {
                    className: "sb-cat-api-types",
                    collapsed: true,
                    customProps: {
                        badge: "types",
                    },
                    items: [
                        {
                            dirName: "developer/api/type-aliases",
                            type: "autogenerated",
                        },
                    ],
                    label: "🧠 Type Aliases",
                    link: {
                        description:
                            "Type-level contracts and shared type aliases exposed by the plugin.",
                        title: "Type Aliases",
                        type: "generated-index",
                    },
                    type: "category",
                },
                {
                    className: "sb-cat-api-runtime",
                    collapsed: true,
                    customProps: {
                        badge: "runtime",
                    },
                    items: [
                        {
                            dirName: "developer/api/variables",
                            type: "autogenerated",
                        },
                    ],
                    label: "⚙️ Runtime Exports",
                    link: {
                        description:
                            "Runtime values and configuration exports from eslint-plugin-etc-misc.",
                        title: "Runtime Exports",
                        type: "generated-index",
                    },
                    type: "category",
                },
            ],
        },
    ],
};

export default sidebars;
